### ISSUE TITLE
Epic: Frontend component packaging

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#145]
A little bit more complex. Needs:
* [x] Clean frontend installation and (path) definitions
* [x] Registry for new plugins to submit their assets etc
* [ ] A clean way to remove assets again (to uninstall packages)
* [x] Integration of js into the frontend app

**Comment by ri0t** [comment]
* [ ] browserify npm deps ( e.g. http://dontkry.com/posts/code/using-npm-on-the-client-side.html )
* [ ] browserify-bower ( https://github.com/tobiash/grunt-browserify-bower )
* [ ] wire up deps
* [ ] frontend builder
 * [ ] collecting
 * [ ] deploying

**Comment by ri0t** [comment]
I am SO done with this for now ;D
