### ISSUE TITLE
Task enhancements for project module

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#338]
* [ ] Selected tasks should be able to expire gracefully 
  * [ ] to a custom taskgroup
  * [ ] soon expiring should be well visible
* [ ] Finalize the referencing system
* [ ] Create calendar entry from tasks with a duration -> for Gantt etc #219 
* [ ] Finalize github importer (mentioned in #219, as well)
* [ ] Notifications about expiring tasks (blocked by: #328)
