### ISSUE TITLE
Epic: MapView sharing support

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#43]
MapViews are leaflet viewport center indicators simply built thus:
{'lat': 12.345, 'lon': 6.789, 'zoom': 12} (See hfos/schemata/coords.py)

They shall be shareable and changes to them subscriptable by clients so the map controller can synchronize views from users.

Needs quite some things:
Node:
- [x] MapView Schemata
- [x] Database factory
- [x] Handling Component
 - [x] Storage of updates
 - [x] Broadcast of updates
 - [x] Subscription management
  - [x] Actions
  - [x] Listing

Client:
- [x] Local MapView change notification
- [x] Broadcast evaluation
- [x] Listing of shared views
- [x] Subscription actions
- [x] Add n..n relationship for Maps/Mapviews

**Comment by ri0t** [comment]
Most of the features are in, i need to change the UUID Client/User handling and already prepared a dia schema for that

**Comment by ri0t** [comment]
Aaalmost done =)

**Comment by ri0t** [comment]
Yaaay! The objectmanager now fully supports this process - a milestone in itself, as that is the basis for many other things.
