### ISSUE TITLE
Epic: User generated geojson

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#44]
* [x] Frontend integration
 * [x] Leaflet.Draw configuration
 * [x] Data handling
 * [x] Preliminary transmission to node
* [x] Schemata for encapsulating object
 * [ ] GeoJSON schemata
* [x] Accept sent layer data from clients
* [x] Store data to the db with uuid reference
* [x] Return a list of shared & own content
* [x] Return geoJSON from db on request
