### ISSUE TITLE
Epic: Documentation

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#47]
* [ ] Add an online lecture/tutorial (1.0)
* [ ] Screencasts for all elements ((half-)automated, via tests?)
* [ ] Frontend Docs (some 1.0)
* [ ] Backend Docs
 * [x] Docstrings (not yet perfect)
* [ ] Printable Docs/Manual?
* [x] Coverage management!
* [x] Demo component
 * [ ] Flesh out demo playback
 * [ ] generate/aquire demo content

**Comment by ri0t** [comment]
@ij0n can you help out, once i have a rough draft of a working system?

**Comment by ri0t** [comment]
I'm doing tests with sphinx, since it is what circuits (the framework) uses
