### ISSUE TITLE
Epic: Remote Control

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#49]
* [x] Controller settings
* [x] Controllables
* [ ] Controllable feedback
* [x] Basic Gamepad/Joystick interface
* [ ] Transmitter/Target coupling
* [ ] Controller settings interface

**Comment by ri0t** [comment]
I need to get my e-lab up and runningn finally, to get the atmega to work the servo.

**Comment by ri0t** [comment]
We're not taking the MS0x00 to camp :(
