### ISSUE TITLE
Epic: Offline seamaps

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#50]
* [x] Initial smrender setup & testing
* [x] [rendered Helgoland](http://soup.hackerfleet.org/post/575237592/Well-this-would-be-your-offline-seamap) using only offline data
* [ ] Checkout daemon
* [ ] Integrate into backend
* [ ] Build clientside render map selector (rectangle selection)
* [ ] Download OSeaM data
* [ ] Limiting
 * [ ] By OSM limits? (How do editors like JOSM know what can be downloaded?)
 * [ ] By rendering time estimation (uh oh)
 * [ ] Limit to maximum effective rendered area (in highest zoom level) instead?
* [ ] Caching and distribution of rendered data
* [ ] Handling of rendered maps' metainfo
 * [ ] update & rerender
 * [ ] std operations

**Comment by ri0t** [comment]
Not enough time and we have cached offline maps :)
