### ISSUE TITLE
Epic: Set up a live web demo

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#51]
Needs quite some work:
* ~~autoreset every x hours~~
* [x] webserver reinstall for docker and frontend
* [x] webserver backend adaption
* [x] webserver frontend adaptations

**Comment by ri0t** [comment]
Now that the docker container works, this should be easy.

**Comment by ri0t** [comment]
Just needs a bit more of wiring and QA, then it'll work.

**Comment by ri0t** [comment]
The url is still private to avoid premature explosions.
