### ISSUE TITLE
Automatic Checklist Generation

### ISSUE THREAD

**Issue by ij0n** [Hackerfleet/hfos#73]
When the Vesselstatus changes, or the Weather, a list of Checkpoints can be generated from the informations about the existing equipment and vesselparameters. This List can include regular occurring items ("check oil pressure hourly"), or items, that are occuring depending on distance travelled ("check jib roller every 500nm sailed"), or items that can only be checked when a special vessel state is active ("check anodes every 6 months, but only if vessel status is "on land/in drydock")

Other examples could be "check vacuum cleaner lashing on bridge when weather changes from light to heavy" or "check lashings of FRB (fast rescue boat) when windspeeds of more then 40kn are expected within 4h"

obvious examples are "check fire extinguishers every 2 years"

The checklistgenerator should take into account, that not all crew is able to check every piece of equipment, the equipmentmanagement should for each piece of equipment therefore include a list of people, that are capable of performing the check. 

Checklists should be compatible with shifts of the crew - only crew on shift should get checklist items. If in an emergency, or in a "all hands on deck" situation, everybody can get tasks on the personal list.

**Comment by ri0t** [comment]
With the new project and task management system in place as well as some general basic features recently implemented, this becomes viable!

**Comment by ri0t** [comment]
This has become very feasible. Major dependencies for a fully (as above) fledged variant of this:
* [x] Be able to get notifications of navdata
* [x] Alerting system to notify of such changes
* [ ] Detailed (geographic) Weather information source
* [ ] A way to construct/provide checklists (ChecklistGenerator)
* [ ] Crew scheduling
