### ISSUE TITLE
Epic: Wiki service

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#79]
Wiki service that could actually be used as generic user generated text blob.
* [x] backend component
* [x] service
 * [x] get pagelist
 * [x] get page
 * [x] notification on pagechanges
 * [x] put page 
* [x] controller
 * [x] simple display mode
 * [x] markup editor
 * [ ] misc wiki functions
* [ ] wiki structure
* [ ] wiki links

**Comment by ri0t** [comment]
An index is already generated. What else do we crucially need?
* [ ] Picture upload (another epic topic!)
