### ISSUE TITLE
Epic: Navigational Data

### ISSUE THREAD

**Issue by ri0t** [Hackerfleet/hfos#92]
* [x] Backend
  * [x] Generate list of navdata items
  * [x] Schemata for the necessary data
  * [x] Component that assesses the data
  * [x] NavState that is distributed to the client's navdata service
* [x] Frontend
 * [x] Service

**Comment by ri0t** [comment]
I've generated a list of navigational data we can get from the ship's bus.

**Comment by ri0t** [comment]
Blocked by #92

**Comment by ri0t** [comment]
Yay, a bit hacky, but a first draft of the navdata backend component is ready. It is crafted rather procotol agnostic and should be easily extendable.

**Comment by ri0t** [comment]
\o/
